### PR TITLE
Mock ReactiveVar, Templating, Tracker

### PR DESCRIPTION
**Pull request by chmac**
Added some mocks which we're using locally that extend the coverage a little.

### CODE REVIEW

**Comment by tomscholz** [comment]
I've had a some pretty busy weeks, but today/tomorrow is a national holiday and I will look into it :) 
If I forget to look into it hit me up at uhupater+github@gmail.com

**Comment by chmac** [comment]
@tomscholz Ping!

**Comment by tomscholz** [comment]
Pong!

**Comment by tomscholz** [comment]
I've just released v1.9.0 and v2.0.0 to npm. v1.9.0 contains your changes and because https://github.com/tomscholz/meteor-jest-stubs/pull/9 contained breaking changes I went ahead and created a new release for it v2.0.0 :)

**Pull request merged**
